### PR TITLE
added csrf support

### PR DESCRIPTION
**Pull request by marionnewlevant**
csrf support, handle non-regex matches, tiny change in edit instructions.
I think this fixes your issue #6 too.
(struggling with understanding github pull requests, and hope I've got it right)

### CODE REVIEW

**Comment by mattstein** [comment]
@rkingon Stuck on #6 and this PR would be a big help. Do you think you might have time to review?

**Comment by mattstein** [comment]
(And @marionnewlevant, your pull request looks lovely. Thanks for sharing so much work and expertise all over the place!)

**Comment by rkingon** [comment]
merged :) -- sorry guys, have been so busy on client projects haven't had time to give this any love.

will soon rebuild and use elementTypes, ect

**Comment by mattstein** [comment]
I've many an unfinished thing for the same reason, so no worries! Thanks for the prompt update though, @rkingon.

**Pull request merged**
